name: C/C++ CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GoogleTest
        run: sudo apt install libgtest-dev

      - name: Compile
        run: make all

      - name: Run tests
        run: make test
